let movies = [{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'},
{title:'Jurasic Hunt',img:'https://m.media-amazon.com/images/M/MV5BZjQ5YjcyOGUtMTljOS00MzMwLWIxNjYtOGMzN2E2MDM5ODlmXkEyXkFqcGdeQXVyODEwNDQ0Mzc@._V1_.jpg',description:'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades.'}
]
export default movies;